### ISSUE TITLE
build fails on mac os x

### ISSUE THREAD

**Issue by agiertli** [chewiebug/GCViewer#192] opened 2017-09-06 06:19 UTC
```
$ git clone
$ mvn clean install
```

Fails with
`INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   GCViewerTest.singleArgumentWithSeriesOpensGui:65
Expected: an empty string
     but: was "GC (Allocation Failure); ParNew [n, avg, sum, min, max]:\t254\t0.005871465354330706\t1.4913521999999992\t0.0025458\t0.0720804\nGC (CMS Final Remark); CMS-remark [n, avg, sum, min, max]:\t3\t0.022280166666666667\t0.0668405\t0.014546400000000001\t0.035476799999999996\nGC (CMS Final Remark); ParNew [n, avg, sum, min, max]:\t3\t0.006661166666666666\t0.019983499999999998\t0.0047071\t0.0090755\nGC (CMS Initial Mark); CMS-initial-mark [n, avg, sum, min, max]:\t3\t0.0064985\t0.0194955\t0.0012955\t0.0164077\nCMS-concurrent-abortable-preclean [n, avg, sum, min, max]:\t3\t0.8973333333333334\t2.692\t0.146\t2.165\nCMS-concurrent-abortable-preclean-start [n, avg, sum, min, max]:\t3\t0.0\t0.0\t0.0\t4.9E-324\nCMS-concurrent-mark [n, avg, sum, min, max]:\t3\t0.11966666666666666\t0.359\t0.044\t0.168\nCMS-concurrent-mark-start [n, avg, sum, min, max]:\t3\t0.0\t0.0\t0.0\t4.9E-324\nCMS-concurrent-preclean [n, avg, sum, min, max]:\t3\t0.002\t0.006\t0.002\t0.002\nCMS-concurrent-preclean-start [n, avg, sum, min, max]:\t3\t0.0\t0.0\t0.0\t4.9E-324\nCMS-concurrent-reset [n, avg, sum, min, max]:\t3\t0.0013333333333333333\t0.004\t0.001\t0.002\nCMS-concurrent-reset-start [n, avg, sum, min, max]:\t3\t0.0\t0.0\t0.0\t4.9E-324\nCMS-concurrent-sweep [n, avg, sum, min, max]:\t3\t0.037\t0.11099999999999999\t0.01\t0.072\nCMS-concurrent-sweep-start [n, avg, sum, min, max]:\t3\t0.0\t0.0\t0.0\t4.9E-324\ninitiatingOccupancyFraction (n, avg, stddev, min, max):\t3\t0.18576856788532145\t0.119682073117975\t0.05340769275837825\t0.28636190531989686\nheap size used (n, avg, stddev, min, max):\t263\t377561.19011406845\t52395.866662139655\t38896\t414382\nperm size used\tjava.lang.IllegalStateException: n == 0\ntenured size used (n, avg, stddev, min, max):\t263\t156256.7908745247\t36369.70019099439\t0\t186283\nyoung size used (n, avg, stddev, min, max):\t263\t221304.39923954374\t31389.01555067893\t8046\t245760\n"
[INFO]
[ERROR] Tests run: 332, Failures: 1, Errors: 0, Skipped: 3
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:18 min
[INFO] Finished at: 2017-09-06T08:15:17+02:00
[INFO] Final Memory: 24M/276M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project gcviewer: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/osiris/Documents/work/developing/GCViewer/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

Tried with:

```
$ mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /Users/osiris/Documents/work/developing/apache-maven-3.3.3
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

Build succeeds with
`mvn clean install -Dmaven.test.skip=true`
Either correct the README to use above command or fix the failing test.

**Comment by chewiebug** [comment] 2017-09-07 10:59
Not a very obvious one, since the tests run on Windows + Linux.

I am able to reproduce the error message you posted also on Windows, if I run the tests in parallel. For almost every run I see a different error message in the same test that fails. Do you also see that?

So my guess is, that the tests on your machine run in parallel (I can't see, why, though).

Since I don't have a mac, could you please try to build the following branches
- https://github.com/chewiebug/GCViewer/tree/bugfix/%23192/fix-using-forced-single-thread
- https://github.com/chewiebug/GCViewer/tree/bugfix/%23192/fix-using-not-thread-safe
- https://github.com/chewiebug/GCViewer/tree/bugfix/%23192/fix-rewriting-unittest
and tell me, what the result is for each of them?

Thanks and best regards,
Jörg

**Comment by chewiebug** [comment] 2017-12-25 15:13
Third option mentioned above was merged to develop. Should now work everywhere.

**Closed by chewiebug** 2017-12-25 15:13 UTC
