### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException /proc/meminfo

### ISSUE THREAD

**Issue by Playmate** [chewiebug/GCViewer#142] opened 2015-07-26 07:45 UTC
I've tried to view gc logs but got an exception, here is my code :
public  class Main {
    public static void main(String[] args) {
        System.out.println("Hello world");
    }
}

jdk 1.8.0_25
OS X Yosemite 10.10.4
VM args : -Xloggc:mygc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps

log file is attached 
<img width="640" alt="screen shot 2015-07-26 at 10 43 45" src="https://cloud.githubusercontent.com/assets/4592740/8892979/08cf7b32-3383-11e5-806c-42dfac88cf88.png">

I used gcviewer-1.35-SNAPSHOT and I got this :
INFO [DataReaderFacade]: GCViewer version n/a (n/a)
INFO [DataReaderFactory]: File format: Sun 1.5.x
INFO [DataReaderSun1_6_0]: Reading Sun / Oracle 1.4.x / 1.5.x / 1.6.x / 1.7.x / 1.8.x format...
INFO [DataReaderSun1_6_0]: Java HotSpot(TM) 64-Bit Server VM (25.25-b02) for bsd-amd64 JRE (1.8.0_25-b17), built on Sep 17 2014 16:56:50 by "java_re" with gcc 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
INFO [DataReaderSun1_6_0]: Memory: 4k page, physical 8388608k(269068k free)
WARNING [DataReaderSun1_6_0]: com.tagtraum.perf.gcviewer.imp.ParseException: Error parsing entry (java.lang.ArrayIndexOutOfBoundsException: 14) Line 4: /proc/meminfo:
INFO [DataReaderSun1_6_0]: CommandLine flags: -XX:InitialHeapSize=134217728 -XX:MaxHeapSize=2147483648 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseParallelGC 
INFO [DataReaderSun1_6_0]: Done reading.

What's wrong ? Could you help me please?

**Comment by chewiebug** [comment] 2015-07-29 21:08
Hi,

Thanks for reporting this issue. Since it is a duplicate of #141, I close this issue - please see there for progress.

Best regards,
Jörg

**Closed by chewiebug** 2015-07-29 21:08 UTC
Labels: duplicate

**Comment by Playmate** [comment] 2015-07-30 05:16
I see, thx a lot.
