### ISSUE TITLE
GCViewer can't draw graph for large gc log

### ISSUE THREAD

**Issue by jerryjeremiah** [chewiebug/GCViewer#172] opened 2016-06-03 04:52 UTC
My gc log is over 60MB in size.  GCViewer loads the file without complaint but never redraws the window.  If I minimize and then restore the app it comes up with a completely black graph and does not redraw the screen.  I am uploading the file and an image of what it looks like after it loads the file and I minimize and restore the app.  This is version 1.33 because I don't have a new enough version of Java to run a newer version - they don't allow us to install any software on our computers...

Is there any way (short of using a GCViewer that needs a newer version of Java) to see the graph?

[gc.2015-11-04_21_47.log.zip](https://github.com/chewiebug/GCViewer/files/296927/gc.2015-11-04_21_47.log.zip)
<img width="274" alt="gc" src="https://cloud.githubusercontent.com/assets/16640170/15769036/1ac842a0-29ab-11e6-8876-6b31e524ca21.png">

**Comment by chewiebug** [comment] 2016-06-03 20:22
I currently can't check with the latest version of GCViewer, but I assume, that it would work - there have been quite a few optimisations since 1.33.

So, no, I don't see any other way, than upgrading to the latest version of GCViewer, I am sorry! 

Best regards, 
Jörg

**Comment by vlsi** [comment] 2016-06-04 10:08
@jerryjeremiah , latest GCViewer loads and renders your log just fine for me.

You can split the file in parts and analyze each part on its own.

Major part of your log looks fine, except the very last part of it.
It reads
```
2016-06-03T08:57:37.794+1200: 18274211.841: [GC [PSYoungGen: 0K->0K(349440K)] 116190K->116190K(1048320K), 0.0122280 secs] [Times: user=0.01 sys=0.00, real=0.01 secs]
2016-06-03T08:57:37.807+1200: 18274211.853: [Full GC [PSYoungGen: 0K->0K(349440K)] [ParOldGen: 116190K->116170K(698880K)] 116190K->116170K(1048320K) [PSPermGen: 65535K->65535K(65536K)], 0.3109470 secs] [Times: user=0.64 sys=0.00, real=0.31 secs]
2016-06-03T08:57:38.120+1200: 18274212.167: [GC [PSYoungGen: 3754K->48K(349440K)] 119924K->116218K(1048320K), 0.0110670 secs] [Times: user=0.02 sys=0.00, real=0.01 secs]
2016-06-03T08:57:38.131+1200: 18274212.178: [Full GC [PSYoungGen: 48K->0K(349440K)] [ParOldGen: 116170K->116190K(698880K)] 116218K->116190K(1048320K) [PSPermGen: 65535K->65535K(65536K)], 0.3340140 secs] [Times: user=0.65 sys=0.00, real=0.33 secs]
```

This looks odd since GC is initiated with almost zero utilization of young gen ==> it might be caused by allocation of large objects.
I mean something like:
```java
while (true) {
  try {
    new byte[900*1024*1024];
  } catch(OutOfMemoryError e) {
    /* ignore */
  }
}
```

Do you have `-XX:+HeapDumpOnOutOfMemoryError` in place? Did it produce any heap dumps?

Upgrading java version (to 1.8) would help as well: it would print GC causes for the GC events.

**Comment by jerryjeremiah** [comment] 2016-06-04 10:22
Thank you so much for the help and all the advice.  On the server we are constrained to Tomcat 6 and Java 1.6 because that's all the application vendor supports.  On the desktop we have JRE 1.7 pre installed but have no ability to update any software or install anything - corporate security.  I will install Java 1.8 at home and have a look - taking the log home is against the rules but I think is necessary now.
I appreciate your advice.
Jerry


Sent from Yahoo Mail on Android 
 
  On Sat, 4 Jun, 2016 at 10:08 pm, Vladimir Sitnikov<notifications@github.com> wrote:   
@jerryjeremiah , latest GCViewer loads and renders your log just fine for me.

You can split the file in parts and analyze each part on its own.

Major part of your log looks fine, except the very last part of it.
It reads
2016-06-03T08:57:37.794+1200: 18274211.841: [GC [PSYoungGen: 0K->0K(349440K)] 116190K->116190K(1048320K), 0.0122280 secs] [Times: user=0.01 sys=0.00, real=0.01 secs]
2016-06-03T08:57:37.807+1200: 18274211.853: [Full GC [PSYoungGen: 0K->0K(349440K)] [ParOldGen: 116190K->116170K(698880K)] 116190K->116170K(1048320K) [PSPermGen: 65535K->65535K(65536K)], 0.3109470 secs] [Times: user=0.64 sys=0.00, real=0.31 secs]
2016-06-03T08:57:38.120+1200: 18274212.167: [GC [PSYoungGen: 3754K->48K(349440K)] 119924K->116218K(1048320K), 0.0110670 secs] [Times: user=0.02 sys=0.00, real=0.01 secs]
2016-06-03T08:57:38.131+1200: 18274212.178: [Full GC [PSYoungGen: 48K->0K(349440K)] [ParOldGen: 116170K->116190K(698880K)] 116218K->116190K(1048320K) [PSPermGen: 65535K->65535K(65536K)], 0.3340140 secs] [Times: user=0.65 sys=0.00, real=0.33 secs]

This looks odd since GC is initiated with almost zero utilization of young gen ==> it might be caused by allocation of large objects.
I mean something like:
while (true) {
  try {
    new byte[900*1024*1024];
  } catch(OutOfMemoryError e) {
    /* ignore */
  }
}
Do you have -XX:+HeapDumpOnOutOfMemoryError in place? Did it produce any heap dumps?

Upgrading java version (to 1.8) would help as well: it would print GC causes for the GC events.

**Comment by chewiebug** [comment] 2016-06-04 17:32
Seeing those two full gc events, I'd say that PermGen is the reason for the gc - it remains full also after the full gc. Either perm gen is just too small, or there is something leaking into perm gen.

**Comment by vlsi** [comment] 2016-06-04 17:35
@chewiebug , you are right. Permgen is the issue here

**Comment by jerryjeremiah** [comment] 2016-06-04 19:58
Thanks for the suggestions.
The application vendor only supports the 32 bit JVM even though we are on a 64 bit Linux kernel so we have played with the sizes and of we make the max heap any larger Tomcat won't start at all.
Something must be leaking into Perm Gen.  I need to figure out how to tell what it is...
Thanks again
Jerry
Sent from Yahoo Mail on Android 
 
  On Sun, 5 Jun, 2016 at 5:35 am, Vladimir Sitnikov<notifications@github.com> wrote:   
@chewiebug , you are right. Permgen is the issue here

**Comment by vlsi** [comment] 2016-06-04 20:10
@jerryjeremiah ,  can you please doublecheck if Tomcat would boot with -XX:MaxPermSize=128m?
I think it should even though you are using 32bit jvm.

**Comment by chewiebug** [comment] 2016-08-01 14:47
I won't implement the original request of this issue (backport to 1.33 / Java 7), so I close the issue here.

It looks like, there was still some progress for the underlying issue.

**Closed by chewiebug** 2016-08-01 14:47 UTC
Labels: won't do

**Comment by jerryjeremiah** [comment] 2021-04-16 05:09
Thanks very much for all the help.  We did in the end find the issue and it was, as you predicted, the Tomcat database connection pool allocating space for a result set containing gazillions of rows because of a roque SQL statement.  I really do appreciate your help - it did make a difference.
